In [1]:
import os
import numpy as np
import aocd
from aocd.models import Puzzle
from aocd import submit

In [2]:
current_day = 11
current_year = 2021
puzzle = Puzzle(year=current_year, day=current_day)
puzzle

<Puzzle(2021, 11) at 0x7ffe1160e100 - Dumbo Octopus>

In [3]:
data = puzzle.input_data.splitlines()
data

['3265255276',
 '1537412665',
 '7335746422',
 '6426325658',
 '3854434364',
 '8717377486',
 '4522286326',
 '6337772845',
 '8824387665',
 '6351586484']

# Part 1

In [4]:
test_input1 = """11111
19991
19191
19991
11111""".splitlines()
test_input2 = """5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526""".splitlines()

In [9]:
from collections import deque

In [46]:
def process_input(input_data, num_steps):
    data = np.array([list(map(int,line)) 
                     for line in input_data])
    rows,cols = data.shape
    num_flashes = 0
    for step in range(num_steps):
        data += 1
        seen = set()
        queue = deque(list(zip(*np.nonzero(data>9))))
        while queue:
            i,j = queue.popleft()
            if (i,j) in seen:
                continue
            seen.add((i,j))
            for ii in range(max(i-1,0),min(i+2,rows)):
                for jj in range(max(j-1,0),min(j+2,cols)):
                    if (ii,jj) not in seen:
                        data[ii,jj] += 1
                        if data[ii,jj] > 9:
                            queue.append((ii,jj))
        num_flashes += len(seen)
        if len(seen) == rows*cols:
            print(step+1)
            return
        for i,j in list(seen):
            data[i,j] = 0
    return data, num_flashes

In [47]:
process_input(test_input1,2)

(array([[4, 5, 6, 5, 4],
        [5, 1, 1, 1, 5],
        [6, 1, 1, 1, 6],
        [5, 1, 1, 1, 5],
        [4, 5, 6, 5, 4]]),
 9)

In [48]:
process_input(test_input2,100)

(array([[0, 3, 9, 7, 6, 6, 6, 8, 6, 6],
        [0, 7, 4, 9, 7, 6, 6, 9, 1, 8],
        [0, 0, 5, 3, 9, 7, 6, 9, 3, 3],
        [0, 0, 0, 4, 2, 9, 7, 8, 2, 2],
        [0, 0, 0, 4, 2, 2, 9, 8, 9, 2],
        [0, 0, 5, 3, 2, 2, 2, 8, 7, 7],
        [0, 5, 3, 2, 2, 2, 2, 9, 6, 6],
        [9, 3, 2, 2, 2, 2, 8, 9, 6, 6],
        [7, 9, 2, 2, 2, 8, 6, 8, 6, 6],
        [6, 7, 8, 9, 9, 9, 8, 7, 6, 6]]),
 1656)

In [49]:
process_input(data,100)

(array([[4, 4, 5, 7, 0, 0, 0, 0, 2, 1],
        [4, 5, 7, 2, 3, 4, 4, 3, 2, 1],
        [5, 7, 1, 1, 1, 1, 1, 1, 1, 8],
        [7, 2, 1, 1, 1, 1, 1, 1, 2, 8],
        [0, 4, 2, 1, 2, 3, 4, 4, 5, 0],
        [0, 0, 5, 4, 5, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]]),
 1627)

In [41]:
puzzle.answer_a = 1627

That's the right answer!  You are one gold star closer to finding the sleigh keys. [Continue to Part Two]


# Part 2

In [50]:
process_input(test_input2,200)

195


In [51]:
process_input(data,1000)

329


In [52]:
puzzle.answer_b = 329

That's the right answer!  You are one gold star closer to finding the sleigh keys.You have completed Day 11! You can [Shareon
  Twitter
Mastodon] this victory or [Return to Your Advent Calendar].
